# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rightscale-api}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Michael"]
  s.date = %q{2010-01-28}
  s.description = %q{A Ruby Wrapper for the RightScale API}
  s.email = %q{david.michael@sonymusic.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/rightscale.rb",
     "lib/rightscale/api.rb",
     "lib/rightscale/client.rb",
     "lib/rightscale/deployments.rb",
     "lib/rightscale/right_scripts.rb",
     "lib/rightscale/servers.rb",
     "lib/rightscale/statuses.rb",
     "pkg/rightscale-api-0.0.1.gem",
     "rightscale-api.gemspec"
  ]
  s.homepage = %q{http://github.com/dmichael/rightscale-api}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Ruby Wrapper for the RightScale API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

